services:
  backend:
    build:
      context: ./01-backend-nodejs
    env_file:
      - ./01-backend-nodejs/.env
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./00-fontend-react
    env_file:
      - ./00-fontend-react/.env
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend-nodejs/02-database-postgresql/linglooma_update.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
