version: "3.8"
services:
  backend:
    build:
      context: ./01-backend-nodejs
    env_file:
      - ./01-backend-nodejs/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./01-backend-nodejs:/app/src
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./00-frontend-react
    env_file:
      - ./00-frontend-react/.env
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:15
    env_file:
      - ./01-backend-nodejs/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: linglooma
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./02-database-postgresql/linglooma_update.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db_data:
